### ISSUE TITLE
Bug in Matlab

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#597] opened 2021-12-04 18:40 UTC
There seems to be a bug in Matlab (at least R2020b) when calling `cellfun` onto a cell array of classes... Here is the case I obtained:
```
>> groups = {replab.S(2), replab.S(3)}

groups =

  1×2 cell array

    {1×1 replab.SymmetricGroup}    {1×1 replab.SymmetricGroup}

>> cellfun(@(x) x.order, groups)
ans =
    2
```
instead of 
```
>> cellfun(@(x) x.order, groups)
ans =
     2     6
```

This situation occurs at least at the following point (maybe in more):
https://github.com/replab/replab/blob/0d8fef1fbd447275f46ddc024014b434b6a977c8/src/%2Breplab/%2Bgen/FiniteGroupType.m#L70

**Comment by jdbancal** [comment] 2021-12-04 18:43
Maybe this occurs because the output of `order` is of type `vpi`? At least, the following code works:
```
K>> cellfun(@(x) x.order, groups, 'UniformOutput', false)

ans =

  1×2 cell array

    {1×1 vpi}    {1×1 vpi}
```

(This bug does not occur in Octave)

**Comment by denisrosset** [comment] 2021-12-07 16:11
Exactly, the problem is with the `vpi` output.

Should I document this in a "bugs" documentation similar to the `octave_bugs` page and close the issue? We're not going to correct the `vpi` class as it is external.

**Comment by denisrosset** [comment] 2021-12-07 18:11
@jdbancal Waiting for your input, will close soon

**Closed** 2021-12-08 14:24 UTC
